basepath = "data/Localization"

locales = ["fr", "de", "it", "pt-BR", "es-ES"]

[[paths]]
reference = "english/*.ini"
l10n = "{locale}/*.ini"

# Map locales to their directory names
[env]
locale_ = { "fr" = "french_(france)", "de" = "german_(germany)", "it" = "italian_(italy)", "pt-BR" = "portuguese_(brazil)", "es-ES" = "spanish_(spain)" }
