basepath = "data/Localization"

locales = [
  "english",
  "french_(france)",
  "german_(germany)",
  "italian_(italy)",
  "portuguese_(brazil)",
  "spanish_(spain)",
]

[env]
l = "{l10n_base}/{locale}"

[[paths]]
reference = "english/*.ini"
l10n = "{l}/*.ini"

[[excludes]]
path = "tools"

[[project]]
name = "StarCitizen Localization"
description = "Localization files for Star Citizen"
version = "4.1.0-LIVE"

[[project.metadata]]
priority = 5
