basepath = "data/Localization"

locales = ["fr", "de", "it", "pt-BR", "es-ES"]

[[paths]]
reference = "{basepath}/en/*.ini"
l10n = "{basepath}/{locale}/*.ini"

[[project]]
[[project.metadata]]
priority = 5
