basepath = "data/Localization"

locales = ["fr", "de", "it", "pt-BR", "es-ES"]

[env]
l = "{l10n_base}/{locale}"

[[paths]]
reference = "english/*.ini"
l10n = "{l}/*.ini"

# [[paths]]
# reference = "english/global.ini"
# l10n = "german_(germany)/global.ini"
# locales = ["en"]

# [[paths]]
# reference = "english/global.ini"
# l10n = "french_(france)/global.ini"
# locales = ["fr"]

# [[paths]]
# reference = "english/global.ini"
# l10n = "german_(germany)/global.ini"
# locales = ["de"]

# [[paths]]
# reference = "english/global.ini"
# l10n = "italian_(italy)/global.ini"
# locales = ["it"]

# [[paths]]
# reference = "english/global.ini"
# l10n = "portuguese_(brazil)/global.ini"
# locales = ["pt-BR"]

# [[paths]]
# reference = "english/global.ini"
# l10n = "spanish_(spain)/global.ini"
# locales = ["es-ES"]

[[excludes]]
path = "tools"

[[project]]
name = "StarCitizen Localization"
description = "Localization files for Star Citizen"
version = "4.1.0-LIVE"

[[project.metadata]]
priority = 5
