basepath = "data/Localization"

locales = ["en", "fr", "de", "it", "pt-BR", "es-ES"]

[map_locales]
en = "english"
fr = "french_(france)"
de = "german_(germany)"
it = "italian_(italy)"
"pt-BR" = "portuguese_(brazil)"
"es-ES" = "spanish_(spain)"

[[paths]]
reference = "english/*.ini"
l10n = "{locale}/*.ini"
