basepath = "data/Localization"

[[paths]]
reference = "english/*.ini"
locales = "en"

[[paths]]
reference = "french_(france)/*.ini"
locales = "fr"

# Map locales to their directory names
# [env]
# locale_ = { "en" = "english", "fr" = "french_(france)", "de" = "german_(germany)", "it" = "italian_(italy)", "pt-BR" = "portuguese_(brazil)", "es-ES" = "spanish_(spain)" }
[[project]]
[[project.metadata]]
priority = 5
