name: Validate global.ini Encoding

on:
  pull_request:
    branches:
      - main
    paths:
      - '*/**/global.ini'

jobs:
  validate-encoding:
    name: Validate global.ini Encoding
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get all "global.ini" files that have changed
        id: changed-files
        uses: tj-actions/changed-files@v39
        with:
          files: data/Localization/**/*.ini

      - name: Validate encoding
        run: tools/validate-encoding.bash ${{ steps.changed-files.outputs.files }}
        # run: tools/validate-encoding.bash "data/Localization/english/global.ini" "data/Localization/french_(france)/global.ini"
